# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               "Leela Chess Zero"
tagline:             'Chess from scratch'
description:         'Official blog of the Leela Chess Zero project.'
url:                 https://lczero.dkappe.com
baseurl:             'https://lczero.dkappe.com'
paginate:            10

# About/contact
author:
  name:              Leela Chess Team
  url:               https://twitter.com/leelachesszero


# Custom vars
excerpt_separator: <!--more-->
logo: https://raw.githubusercontent.com/dkappe/dkappe.github.io/master/public/images/logo.png
