# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               "Leela Chess Zero"
tagline:             'Chess from scratch'
description:         'Official blog of the Leela Chess Zero project.'
url:                 https://blog.lczero.org
baseurl:             'https://blog.lczero.org'
paginate:            10

# About/contact
author:
  name:              Leela Chess Team
  url:               https://twitter.com/leelachesszero
github:
  repo:              https://github.com/LeelaChessZero
rss:
  image:             https://raw.githubusercontent.com/dkappe/dkappe.github.io/master/public/images/72BD29AF-BBDE-484E-981A-204005D35506.png
  url:               /atom.xml
# Custom vars
excerpt_separator: <!--more-->
logo: https://raw.githubusercontent.com/dkappe/dkappe.github.io/master/public/images/logo.png
