# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               "Leela Chess and Non Zero"
tagline:             'Chess and neural networks'
description:         'Blog about Leela Chess Zero and Other Things.'
url:                 https://lczero.libertymedia.io
baseurl:             'https://lczero.libertymedia.io'
paginate:            10

# About/contact
author:
  name:              Dietrich Kappe
  url:               https://lczero.libertymedia.io
github:
  repo:              https://github.com/dkappe/leela-chess-weights
rss:
  image:             https://raw.githubusercontent.com/dkappe/dkappe.github.io/master/public/images/72BD29AF-BBDE-484E-981A-204005D35506.png
  url:               /atom.xml
# Custom vars
excerpt_separator: <!--more-->
logo: https://raw.githubusercontent.com/dkappe/dkappe.github.io/master/public/images/logo.png
public_base: https://raw.githubusercontent.com/dkappe/dkappe.github.io/master/public
